version: "3.9"
volumes:
    db-volume:
services:
    db:
        container_name: sub-db
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        volumes:
            - db-volume:/var/opt/mssql/
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Welcome1234568910"
    api:
        container_name: sub-api
        build:
            context: ./user-browser-backend/
            dockerfile: ./Dockerfile
        depends_on:
            - db
        ports: 
            - "8080:8080"
        environment:
            NODE_APP_ENV: "development"
            NODE_APP_SUB_POSTLOGIN_REDIRECT_URL: sub-app
            NODE_APP_SUB_FRONTEND_URL: "http://localhost"
            NODE_APP_SUB_BACKEND_URL: "http://localhost:8080"
            NODE_APP_SUB_INSECURE_COOKIES: "false" #Must be "false" for production and "true" for localhost or cookies won't be sent and auth won't work
            NODE_APP_SUB_IDP_LOGIN_URL: "https://somedomain.org/crowd/console/secure/saml/sso.action"
            NODE_APP_SUB_IDP_LOGOUT_URL: "https://somedomain.org/crowd/console/logoff.action"
            NODE_APP_SUB_CREATE_DATA: "yes" #If "yes", creates synthetic test data.
            NODE_APP_SUB_SQL_HOSTNAME: sub-db
            NODE_APP_SUB_SQL_DATABASE: "tempdb"
            NODE_APP_SUB_SQL_USERNAME: "sa"
            NODE_APP_SUB_SQL_PASSWORD: "Welcome1234568910"
            NODE_APP_SUB_SESSION_SECRET: "changeme"
            NODE_APP_SUB_IDP_ISSUER: "some-issuer-value"
            NODE_APP_SUB_IDP_CERT: "some-cert-value-as-one-line-without-begin-and-end-tags"
    front:
        container_name: sub-app
        build:
            context: ./user-browser/
            dockerfile: ./Dockerfile
        depends_on:
            - api
            - db
        ports: 
            - "80:80"
        environment:
            REACT_APP_SUB_API_URL: sub-api
            REACT_APP_SUB_ADMIN_SG_ID: "some-admin-security-group"
            REACT_APP_SUB_WRITE_SG_ID: "some-readwrite-security-group"